# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-03 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20170803_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseorg',
            old_name='studnet',
            new_name='studnets',
        ),
    ]
